openapi: 3.2.0
info:
  description: '<p>Provides the Oracle REST Data Services (ORDS) users the ability to perform Oracle Database management and monitoring operations through a user-friendly REST API. Depending on the database version and configuration, ORDS database APIs provide services such as manage pluggable databases, export data, and review database performance.</p><p>To install and configure Oracle REST Data Services refer to the <a href=https://docs.oracle.com/pls/topic/lookup?ctx=ords-latest&id=ORDIG> Oracle&reg REST Data Services Installation and Configuration Guide</a>.</p>

    <p>An OpenAPI V3 document that describes the available ORDS database API services can be retrieved from a running ORDS instance. The API document can be imported into compatible development tools and invoked from there. The URL to retrieve the API document depends on the your configuration. <p><p>The pattern for the API document URL is: </p>

    <code>https://&lt;server&gt;/&lt;context root&gt;/&lt;my database&gt;/&lt;my schema&gt;/_/db-api/stable/&lt;service path&gt;  </code>

    <p>Where, the <code>&lt;my database&gt;</code> and  <code>&lt;my schema&gt;</code> variables can be optional, depending on the ORDS configuration and the service invoked.'
  version: 2026.03.26
  title: Oracle REST Data Services Vector Database/Vector Indexes API
  contact:
    name: Oracle REST Data Services
    url: https://www.oracle.com/database/technologies/appdev/rest.html
  x-summary: Provides the Oracle REST Data Services (ORDS) users the ability to perform Oracle Database management and monitoring operations through a user-friendly REST API.
tags:
- name: Vector Database/Vector Indexes
  description: The operations from the Vector Database/Vector Indexes category.
paths:
  /vecdb/vector-indexes/:
    post:
      tags:
      - Vector Database/Vector Indexes
      operationId: create_index
      summary: Creates an IVF or HNSW vector index using create_index API.
      description: Creates a vector index using create_index API.
      security:
      - BasicAuth: []
      - BearerAuth: []
      - OAuth2: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
              - tableName
              properties:
                tableName:
                  type: string
                  description: The name of the vector table.
                indexParams:
                  type: object
                  description: Parameters required to create the vector index.
                  properties:
                    organization:
                      type: string
                    advanced_params:
                      type: object
                debugFlags:
                  $ref: '#/components/schemas/VectorDebugFlags'
      responses:
        '200':
          description: Description of the vector index creation job that has been created.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/VecDBJobItem'
        '400':
          description: The request body included invalid parameters.
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/ORDSErrorResponse'
        '404':
          description: The vector table was not found.
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/ORDSErrorResponse'
      x-internal-id: vecdb-vector-indexes--post
      x-filename-id: vecdb-vector-indexes-post
  /vecdb/vector-indexes/jobs/:
    get:
      tags:
      - Vector Database/Vector Indexes
      operationId: list_index_jobs
      summary: Retrieve all schedulled vector indexes jobs.
      description: Describes all of the jobs scheduled to create or rebuild a vector index.
      security:
      - BasicAuth: []
      - BearerAuth: []
      - OAuth2: []
      responses:
        '200':
          description: Description of all the jobs that have been created.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/VecDBJobCollection'
      x-internal-id: vecdb-vector-indexes-jobs--get
      x-filename-id: vecdb-vector-indexes-jobs-get
  /vecdb/vector-indexes/jobs/{index_job_name}/:
    get:
      tags:
      - Vector Database/Vector Indexes
      operationId: describe_index_job
      summary: Retrieve details of an schedulled vector index job.
      description: Describes the specified job scheduled to create a vector index.
      security:
      - BasicAuth: []
      - BearerAuth: []
      - OAuth2: []
      parameters:
      - name: index_job_name
        in: path
        description: The name of the vector index job.
        required: true
        schema:
          type: string
      responses:
        '200':
          description: Description of the vector index creation or rebuild job that have been created.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/VecDBJobItem'
        '404':
          description: The specified index job was not found.
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/ORDSErrorResponse'
      x-internal-id: vecdb-vector-indexes-jobs-{index_job_name}--get
      x-filename-id: vecdb-vector-indexes-jobs-index_job_name-get
  /vecdb/vector-indexes/jobs/{index_job_name}/jobfile:
    get:
      tags:
      - Vector Database/Vector Indexes
      operationId: get_index_job_log
      summary: Get the logs associated to a scheduled vector index job.
      description: Returns the log associated to a given vector index job.
      security:
      - BasicAuth: []
      - BearerAuth: []
      - OAuth2: []
      parameters:
      - name: index_job_name
        in: path
        description: The name of the load job.
        required: true
        schema:
          type: string
      responses:
        '200':
          description: Description of the vector index creation or rebuild jobs that have been created.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/VecDBJobLogItem'
        '404':
          description: The specified index job was not found or the index job has not finished yet.
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/ORDSErrorResponse'
      x-internal-id: vecdb-vector-indexes-jobs-{index_job_name}-jobfile-get
      x-filename-id: vecdb-vector-indexes-jobs-index_job_name-jobfile-get
  /vecdb/vector-indexes/{vector_table_name}:
    post:
      tags:
      - Vector Database/Vector Indexes
      operationId: rebuild_index
      summary: Updates an existing IVF or HNSW vector index using the rebuild_index API.
      description: Rebuilds the index associated to the specified vector table. A index can be rebuilded with different parameters
      security:
      - BasicAuth: []
      - BearerAuth: []
      - OAuth2: []
      parameters:
      - name: vector_table_name
        in: path
        description: The name of the vector table to which the vector index is associated to.
        required: true
        schema:
          type: string
      requestBody:
        required: false
        content:
          application/json:
            schema:
              type: object
              properties:
                indexParams:
                  type: object
                  description: Parameters required to create the vector index.
                  properties:
                    organization:
                      type: string
                    advanced_params:
                      type: object
                debugFlags:
                  $ref: '#/components/schemas/VectorDebugFlags'
      responses:
        '200':
          description: Description of the index rebuild job that has been created.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/VecDBJobItem'
        '400':
          description: The request body included invalid parameters.
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/ORDSErrorResponse'
        '404':
          description: The vector table was not found.
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/ORDSErrorResponse'
      x-internal-id: vecdb-vector-indexes-{vector_table_name}-post
      x-filename-id: vecdb-vector-indexes-vector_table_name-post
    get:
      tags:
      - Vector Database/Vector Indexes
      operationId: describe_index
      summary: Retrieves the status of the vector index associated to the requested vector table.
      description: Get information about the status of a vector index.
      security:
      - BasicAuth: []
      - BearerAuth: []
      - OAuth2: []
      parameters:
      - name: vector_table_name
        in: path
        description: The name of the vector table to which the vector index is associated to.
        required: true
        schema:
          type: string
      responses:
        '200':
          description: Status of the vector index
          content:
            application/json:
              schema:
                type: object
                properties:
                  Index Status:
                    type: string
        '400':
          description: The request body included invalid parameters.
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/ORDSErrorResponse'
        '404':
          description: The vector table was not found.
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/ORDSErrorResponse'
      x-internal-id: vecdb-vector-indexes-{vector_table_name}-get
      x-filename-id: vecdb-vector-indexes-vector_table_name-get
    delete:
      tags:
      - Vector Database/Vector Indexes
      operationId: drop_index
      summary: Drops a vector index.
      description: 'Drops the vector index associated to the specified vector table. '
      security:
      - BasicAuth: []
      - BearerAuth: []
      - OAuth2: []
      parameters:
      - name: vector_table_name
        in: path
        description: The name of the vector table to which the vector index is associated to.
        required: true
        schema:
          type: string
      responses:
        '200':
          description: Index dropped
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
        '400':
          description: The request body included invalid parameters.
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/ORDSErrorResponse'
        '404':
          description: The vector table was not found.
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/ORDSErrorResponse'
      x-internal-id: vecdb-vector-indexes-{vector_table_name}-delete
      x-filename-id: vecdb-vector-indexes-vector_table_name-delete
components:
  schemas:
    VectorDebugFlags:
      type: object
      description: Debug flags to be used to trace vector modules
      properties:
        VECTOR_INDEX:
          type: string
          enum:
          - low
          - medium
          - high
        VECTOR_INDEX_NEIGHBOR_GRAPH:
          type: string
          enum:
          - low
          - medium
          - high
        VECTOR_INDEX_NEIGHBOR_GRAPH_BUILD:
          type: string
          enum:
          - low
          - medium
          - high
        VECTOR_INDEX_NEIGHBOR_GRAPH_MEM:
          type: string
          enum:
          - low
          - medium
          - high
        VECTOR_INDEX_NEIGHBOR_GRAPH_SEARCH:
          type: string
          enum:
          - low
          - medium
          - high
        VECTOR_INDEX_NEIGHBOR_GRAPH_APPCHNG:
          type: string
          enum:
          - low
          - medium
          - high
        VECTOR_INDEX_NEIGHBOR_GRAPH_STATS:
          type: string
          enum:
          - low
          - medium
          - high
        VECTOR_INDEX_NEIGHBOR_PARTITIONS:
          type: string
          enum:
          - low
          - medium
          - high
        VECTOR_INDEX_FIXED_VIEW:
          type: string
          enum:
          - low
          - medium
          - high
        VECIDX_TRANS:
          type: string
          enum:
          - low
          - medium
          - high
        VECIDX_TRANS_COM:
          type: string
          enum:
          - low
          - medium
          - high
        VECIDX_TRANS_PJ:
          type: string
          enum:
          - low
          - medium
          - high
        VECIDX_TRANS_PJ_DWNGRD:
          type: string
          enum:
          - low
          - medium
          - high
        VECIDX_TRANS_PJ_GROW:
          type: string
          enum:
          - low
          - medium
          - high
        VECIDX_TRANS_SJ:
          type: string
          enum:
          - low
          - medium
          - high
        VECIDX_TRANS_SJ_BG:
          type: string
          enum:
          - low
          - medium
          - high
        VEC_INDEX_CALIBRATION:
          type: string
          enum:
          - low
          - medium
          - high
        VECTOR_TRACE:
          type: string
          enum:
          - low
          - medium
          - high
    VecDBJobLogItem:
      type: object
      properties:
        log_date:
          type: string
        job_name:
          type: string
        status:
          type: string
        error#:
          type: integer
        additional_info:
          type:
          - string
          - 'null'
        actual_start_date:
          type: string
        run_duration:
          type: string
        links:
          type: array
          items:
            $ref: '#/components/schemas/LinkRelation'
    LinkRelation:
      type: object
      properties:
        rel:
          type: string
        href:
          type: string
      required:
      - rel
      - href
    VecDBJobCollection:
      type: object
      properties:
        items:
          type: array
          items:
            $ref: '#/components/schemas/VecDBJobItem'
        hasMore:
          type: boolean
          description: Indicates if there are more records to be retrieved.
        limit:
          type: integer
          description: The actual page size limit on number of records applied by the server.
        offset:
          type: integer
          description: The actual index from which the item resources are returned.
        count:
          type: integer
          description: Total number of records in the current response.
        links:
          type: array
          items:
            $ref: '#/components/schemas/LinkRelation'
    VecDBJobItem:
      type: object
      properties:
        job_name:
          type: string
        job_creator:
          type: string
        job_type:
          type: string
        operation:
          type: string
        state:
          type: string
        start_date:
          type:
          - string
          - 'null'
        links:
          type: array
          items:
            $ref: '#/components/schemas/LinkRelation'
    ORDSErrorResponse:
      type: object
      required:
      - code
      - message
      - type
      - instance
      properties:
        code:
          type: string
        message:
          type: string
        type:
          type: string
        instance:
          type: string
        diagnosticTrace:
          type: string
        stackTrace:
          type: string
  securitySchemes:
    BasicAuth:
      type: http
      scheme: basic
    BearerAuth:
      type: http
      scheme: bearer
    OAuth2:
      type: oauth2
      flows:
        implicit:
          authorizationUrl: /oauth/auth
          scopes: {}
        authorizationCode:
          authorizationUrl: /oauth/auth
          tokenUrl: /oauth/token
          scopes: {}
        clientCredentials:
          tokenUrl: /oauth/token
          scopes: {}
externalDocs:
  description: Oracle REST Data Services product documentation.
  url: https://docs.oracle.com/en/database/oracle/oracle-rest-data-services/
